module.exports = {
  apps: [
    {
      name: "api-gateway",
      script: "dist/index.js",
      cwd: "./apiGateway",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
    },
    {
      name: "user-service",
      script: "dist/index.js",
      cwd: "./userService",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
    },
    {
      name: "content-service",
      script: "dist/index.js",
      cwd: "./contentService",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 3002,
      },
    },
    {
      name: "question-service",
      script: "dist/index.js",
      cwd: "./questionService",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 3003,
      },
    },
    {
      name: "student-service",
      script: "dist/index.js",
      cwd: "./studentService",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 3004,
      },
    },
    {
      name: "test-service",
      script: "dist/index.js",
      cwd: "./testService",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 3005,
      },
    },
    {
      name: "teacher-service",
      script: "dist/index.js",
      cwd: "./teacherService",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 3006,
      },
    },
    {
      name: "dashboard-service",
      script: "dist/index.js",
      cwd: "./dashboardService",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 3007,
      },
    },
  ],
};
