import Course from "../modules/course/course.model";
import Enrollment from "../modules/enrollment/enrollment.model";
import Location from "../modules/location/location.model";
import PredefinedTest from "../modules/predefinedTest/predefinedTest.model";
import PredefinedTestQuestion from "../modules/predefinedTest/predefinedTestQuestion.model";
import PredefinedTestStudent from "../modules/predefinedTest/predefinedTestStudent.model";
import Question from "../modules/question/question.model";
import Subject from "../modules/subject/subject.model";
import TeacherAssignment from "../modules/teacherAssignment/teacherAssignment.model";
import TestAnswer from "../modules/testAnswer/testAnswer.model";
import TestSelection from "../modules/testSelection/testSelection.model";
import TestSession from "../modules/testSession/testSession.model";
import Topic from "../modules/topic/topic.model";
import User from "../modules/user/user.model";
import UserSkillRating from "../modules/userSkillRating/userSkillRating.model";

Course.hasMany(Subject, { foreignKey: "course_id", as: "subjects" });
Subject.belongsTo(Course, { foreignKey: "course_id", as: "course" });
Subject.hasMany(Topic, { foreignKey: "subject_id", as: "topics" });
Topic.belongsTo(Subject, { foreignKey: "subject_id", as: "subject" });
Question.belongsTo(Topic, { foreignKey: "topic_id", as: "topic" });
Question.belongsTo(Subject, { foreignKey: "subject_id", as: "subject" });
Question.belongsTo(Course, { foreignKey: "course_id", as: "course" });
Topic.hasMany(Question, { foreignKey: "topic_id", as: "questions" });
TeacherAssignment.belongsTo(Course, { foreignKey: "course_id", as: "course" });
TeacherAssignment.belongsTo(Subject, { foreignKey: "subject_id", as: "subject" });
Enrollment.belongsTo(Course, { foreignKey: "course_id", as: "course" });
Enrollment.belongsTo(Subject, { foreignKey: "subject_id", as: "subject" });
Enrollment.belongsTo(Topic, { foreignKey: "topic_id", as: "topic" });
Enrollment.belongsTo(User, { foreignKey: "student_id", as: "student" });
User.hasMany(Enrollment, { foreignKey: "student_id", as: "enrollments" });
TeacherAssignment.belongsTo(User, { foreignKey: "teacher_id", as: "teacher" });
User.hasMany(TeacherAssignment, { foreignKey: "teacher_id", as: "assignments" });
Course.hasMany(TeacherAssignment, { foreignKey: "course_id", as: "teacherAssignments" });
Subject.hasMany(TeacherAssignment, { foreignKey: "subject_id", as: "teacherAssignments" });
TestAnswer.belongsTo(TestSession, { foreignKey: "test_session_id", as: "testSession" });
TestAnswer.belongsTo(Question, { foreignKey: "question_id", as: "question" });
TestSession.hasMany(TestAnswer, { foreignKey: "test_session_id", as: "answers" });
TestSession.hasMany(TestSelection, { foreignKey: "test_session_id", as: "selections" });
TestSelection.belongsTo(TestSession, { foreignKey: "test_session_id", as: "testSession" });
TestSelection.belongsTo(Course, { foreignKey: "course_id", as: "course" });
TestSelection.belongsTo(Subject, { foreignKey: "subject_id", as: "subject" });
TestSelection.belongsTo(Topic, { foreignKey: "topic_id", as: "topic" });
TestSession.belongsTo(Course, { foreignKey: "course_id", as: "course", constraints: false });
TestSession.belongsTo(Subject, { foreignKey: "subject_id", as: "subject", constraints: false });
TestSession.belongsTo(Topic, { foreignKey: "topic_id", as: "topic", constraints: false });
// Predefined Test associations
PredefinedTest.hasMany(PredefinedTestQuestion, { foreignKey: "predefined_test_id", as: "fixedQuestions" });
PredefinedTestQuestion.belongsTo(PredefinedTest, { foreignKey: "predefined_test_id", as: "predefinedTest" });
PredefinedTestQuestion.belongsTo(Question, { foreignKey: "question_id", as: "question" });
PredefinedTest.hasMany(PredefinedTestStudent, { foreignKey: "predefined_test_id", as: "assignedStudents" });
PredefinedTestStudent.belongsTo(PredefinedTest, { foreignKey: "predefined_test_id", as: "predefinedTest" });
PredefinedTestStudent.belongsTo(TestSession, { foreignKey: "test_session_id", as: "testSession" });
TestSession.belongsTo(PredefinedTest, { foreignKey: "predefined_test_id", as: "predefinedTest", constraints: false });
User.belongsTo(Location, { foreignKey: "location_id", as: "location" });
Location.hasMany(User, { foreignKey: "location_id", as: "users" });
